//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YtDlpGuiWpf.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YtDlpGuiWpf.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string bBrowse {
            get {
                return ResourceManager.GetString("bBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string bDownload {
            get {
                return ResourceManager.GetString("bDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string bPaste {
            get {
                return ResourceManager.GetString("bPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EN.
        /// </summary>
        internal static string lang {
            get {
                return ResourceManager.GetString("lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Save Path.
        /// </summary>
        internal static string localSavePath {
            get {
                return ResourceManager.GetString("localSavePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Post-Download Actions.
        /// </summary>
        internal static string postEnablePostActions {
            get {
                return ResourceManager.GetString("postEnablePostActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Remote script.
        /// </summary>
        internal static string postRunRemoteScript {
            get {
                return ResourceManager.GetString("postRunRemoteScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer to Remote.
        /// </summary>
        internal static string postTransToRemote {
            get {
                return ResourceManager.GetString("postTransToRemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Server Configuration.
        /// </summary>
        internal static string remoteServerConfTitle {
            get {
                return ResourceManager.GetString("remoteServerConfTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        internal static string rHost {
            get {
                return ResourceManager.GetString("rHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote OS.
        /// </summary>
        internal static string rOs {
            get {
                return ResourceManager.GetString("rOs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string rPassword {
            get {
                return ResourceManager.GetString("rPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Path.
        /// </summary>
        internal static string rRemotePath {
            get {
                return ResourceManager.GetString("rRemotePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Script Path.
        /// </summary>
        internal static string rRemoteScriptPath {
            get {
                return ResourceManager.GetString("rRemoteScriptPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string rUser {
            get {
                return ResourceManager.GetString("rUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video URL.
        /// </summary>
        internal static string videoUrl {
            get {
                return ResourceManager.GetString("videoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yt-dlp Arguments.
        /// </summary>
        internal static string ytDlpArgs {
            get {
                return ResourceManager.GetString("ytDlpArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yt-dlp Install Path.
        /// </summary>
        internal static string ytDlpInstallPath {
            get {
                return ResourceManager.GetString("ytDlpInstallPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yt-dlp Naming Scheme.
        /// </summary>
        internal static string ytDlpNaming {
            get {
                return ResourceManager.GetString("ytDlpNaming", resourceCulture);
            }
        }
    }
}
